spring.application.name=AtomicGuardAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/atomic_guard
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

//redis-configuration
spring.data.redis.host=redis-12004.crce300.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=12004
spring.data.redis.username=default
spring.data.redis.password=M9hhxkKzQ58Oc9WRWoDSgKM5RKxlciQ6